services:
   convert-image:
      build: .
      container_name: convert-image
      environment:
         - PORT=3008
      restart: unless-stopped
      networks:
         - web-network

networks:
   web-network:
      external: true
